"""empty message

Revision ID: 80845b4e3926
Revises: 632e6f0f20d7
Create Date: 2024-05-16 19:38:43.759966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80845b4e3926'
down_revision = '632e6f0f20d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_confirmed', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('confirmed_on', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('confirmed_on')
        batch_op.drop_column('is_confirmed')

    # ### end Alembic commands ###
