"""empty message

Revision ID: b27de8bd1a81
Revises: 80845b4e3926
Create Date: 2024-05-16 19:50:01.133823

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b27de8bd1a81'
down_revision = '80845b4e3926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.alter_column('cpf',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('telefone',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=25),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed_on', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('confirmed_on')

    with op.batch_alter_table('aluno', schema=None) as batch_op:
        batch_op.alter_column('telefone',
               existing_type=sa.String(length=25),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('cpf',
               existing_type=sa.String(length=200),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
