"""confimações de envio de email

Revision ID: e766d7373051
Revises: 1c3927bd7aef
Create Date: 2024-05-17 21:23:17.667898

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e766d7373051'
down_revision = '1c3927bd7aef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('dev',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.alter_column('admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.alter_column('dev',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)

    # ### end Alembic commands ###
